### ISSUE TITLE
The extension should block invalid package names

### ISSUE THREAD

**Issue by kathrynkodama** [MicroShed/mp-rest-client-generator-vscode-ext#13]
**Current Behaviour**
The extension prompts currently prompts the user for a package directory to generate into (ex. `src/main/java/com`.  
![image](https://user-images.githubusercontent.com/26146482/74047098-cb6f8d00-499d-11ea-81aa-6f29531b7185.png)

Then it will autofill a package name based on the chosen directory (ex. `com` ) but allow for the user to still modify the package name.  
![image](https://user-images.githubusercontent.com/26146482/74047150-dde9c680-499d-11ea-8d55-29aacc60912e.png)

If the user enters a different package name, they will run into a runtime error when they run the project.

**Suggested solutions**
- Do not allow the user to enter a package name.  Autofill the package name based on the initial prompt to generate into.
- If the package name does not match the chosen target directory, deliver a warning to the user or a prompt for them to verify creating directories to match the inputted package name.

Also consider whether a user would generate into a non `src/main/java` directory and what to do in that situation.

**Comment by kathrynkodama** [comment]
Do not allow the user to enter a package name. Autofill the package name based on the initial prompt to generate into. If they did not generate from a `java` directory, generate the `api` and `models` folders into the selected directory and set package names to be `api` and `models`.

**Comment by kathrynkodama** [comment]
Fixed with #18

**Comment by bensonnw** [comment]
Just played around with the extension, I am going to generate the api and model files to "myapp/java/src/com/client" folder, my source folder is "src" , and package name should be "com.client". Using the extension, the generated Java files have the package name "src.com.client..." which is wrong, since no package name prompt up, I can't fix the package name before generating the code.

**Comment by bensonnw** [comment]
Should we always assume "java" is the source folder name?

**Comment by kathrynkodama** [comment]
Given typical java projects structure I would assume the project would be organized `src/main/java`.  Do you think we should not use this assumption?

**Comment by bensonnw** [comment]
For the maven project, that could be the typical project structure, for some eclipse projects I worked on before, the source folder usually using "src" or "main", and java is for the language, since the project could be written in multiple languages.

**Comment by bensonnw** [comment]
Anyway, it's just my 2 cents, we can discuss it in the scrum.
